dist: bionic
language: python
python: "3.8"

services:
  - docker
  - xvfb

addons:
  chrome: stable

before_install:
  - nvm install 14
  - node --version

script:
  - echo "Hello"
  # - pushd frontend/ && yarn install && popd
  # - pushd frontend/ && yarn test:unit && yarn test:e2e && popd
  # - pushd frontend/ && yarn build && popd
  # - pushd backend/ && make install && popd
  # - pushd backend/ && make test && popd

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f38549760c77_key -iv $encrypted_f38549760c77_iv -in ci/travis_rsa.enc -out /tmp/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/travis\_rsa
  - ssh-add /tmp/travis\_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bash ci/deploy.sh
  on:
    branch: master
