language: node_js

services:
  - docker

addons:
  chrome: stable

node_js:
  - '8'

before_script:
  - pushd frontend/ && yarn install && popd
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3


jobs:
  include:
    - stage: test
      script: pushd frontend && yarn test:unit && yarn test:e2e && popd
    - stage: build
      script: pushd frontend && yarn build && popd
    - stage: deploy
      deploy:
        provider: script
        skip_cleanup: true
        script: bash ci/deploy.sh
        on:
          branch: master

after_script:
  - sh -e /etc/init.d/xvfb stop

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f38549760c77_key -iv $encrypted_f38549760c77_iv -in ci/travis_rsa.enc -out /tmp/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/travis\_rsa
  - ssh-add /tmp/travis\_rsa
