language: node_js
services:
  - docker

addons:
  chrome: stable

node_js:
  - '8'

before_script:
  - pushd frontend/ && yarn install && popd
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - pushd frontend && yarn test:unit && popd
  - pushd frontend && yarn build && popd
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t hamvocke/doppelkopf .
  - docker push hamvocke/doppelkopf:latest
  - ./ci/deploy_frontend.sh

after_script:
  - sh -e /etc/init.d/xvfb stop
