language: node_js
services:
  - docker

addons:
  chrome: stable

node_js:
  - '8'

before_script:
  - yarn install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - pushd frontend && yarn test:unit && popd
  - pushd frontend && yarn build && popd
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker-compose build
  - docker-compose push

after_script:
  - sh -e /etc/init.d/xvfb stop
