dist: bionic

language: python

services:
  - docker
  - xvfb

addons:
  chrome: stable

node_js:
  - '12'

matrix:
  include:
    - language: node_js
      node_js: '14'
      before_script:
        - cd frontend/
        - yarn install
      script:
        - yarn test:unit
        - yarn test:e2e
        - yarn build

    - language: python
      python: "3.8"
      before_script:
        - cd backend/
        - make install
      script:
        - make test

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f38549760c77_key -iv $encrypted_f38549760c77_iv -in ci/travis_rsa.enc -out /tmp/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/travis\_rsa
  - ssh-add /tmp/travis\_rsa

deploy:
  provider: script
  cleanup: false
  script: bash ci/deploy.sh
  on:
    branch: master
