language: node_js

services:
  - docker

addons:
  chrome: stable
  ssh_known_hosts: <deploy-host>

node_js:
  - '8'

before_script:
  - yarn install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f38549760c77_key -iv $encrypted_f38549760c77_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

script:
  - yarn test
  - yarn build
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker-compose build
  - docker push hamvocke/doppelkopf:latest

deploy:
  provider: script
  script: ./deploy.sh

after_script:
  - sh -e /etc/init.d/xvfb stop
