language: node_js
services:
  - docker

addons:
  chrome: stable

node_js:
  - '8'

before_script:
  - yarn install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - yarn test:unit
  - yarn build
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t hamvocke/doppelkopf .
  - docker push hamvocke/doppelkopf:latest

after_script:
  - sh -e /etc/init.d/xvfb stop
