version: '3'

services:
  backend:
    build: backend/
    image: hamvocke/doppelkopf_backend:latest
    container_name: doppelkopf-backend
    env_file: backend/.env
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/db:/app/db
    networks:
      - app-network

  webserver:
    build: frontend/
    image: hamvocke/doppelkopf-web:latest
    container_name: doppelkopf-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./caddy_data:/data
    networks:
      - app-network

networks:
  app-network:
