version: '3'

services:
  backend:
    image: hamvocke/doppelkopf-backend:latest
    container_name: doppelkopf-backend
    env_file: backend.env
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
    networks:
      - app-network

  webserver:
    image: hamvocke/doppelkopf-web:latest
    container_name: doppelkopf-web
    env_file: web.env
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./caddy_data:/data
    networks:
      - app-network

networks:
  app-network:
