version: '3'
services:
  frontend:
    restart: always
    build: "./frontend"
    ports:
      - "8088:80"
    image: hamvocke/doppelkopf-backend
    depends_on:
      - backend

  backend:
    restart: always
    build: .
    expose:
      - "5000"
    ports:
      - "5000:5000"
    image: hamvocke/doppelkopf-backend
