version: 2.1

jobs:
  frontend:
    docker:
      - image: circleci/node:14.5.0-browsers
    working_directory: ~/hamvocke/doppelkopf
    steps:
      - checkout
      - attach_workspace:
          at: ~/hamvocke/doppelkopf
      - restore_cache:
          key: v1-frontend-yarn-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install frontend dependencies
          command: 'pushd frontend && yarn install && popd'
      - save_cache:
          key: v1-frontend-yarn-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
      - run:
          name: Test frontend
          command: 'pushd frontend && yarn test:unit && test:e2e && popd'
      - run:
          name: Build frontend
          command: 'pushd frontend && yarn build && popd'
      - persist_to_workspace:
          root: .
          paths: frontend/dist

  backend:
    docker:
      - image: circleci/python:3.8-node-browsers
    working_directory: ~/hamvocke/doppelkopf
    steps:
      - checkout
      - attach_workspace:
          at: ~/hamvocke/doppelkopf
      - restore_cache:
          key: v1-backend-yarn-{{ checksum "backend/yarn.lock" }}
      - run:
          name: Install backend dependencies
          command: 'pushd backend && make install && popd'
      - save_cache:
          key: v1-backend-yarn-{{ checksum "backend/yarn.lock" }}
          paths:
            - backend/node_modules
      - run:
          name: Test backend
          command: 'pushd backend && make test && popd'

workflows:
  version: 2
  build-all:
    jobs:
      - frontend
      - backend
      # - deploy
      #     requires:
      #       - frontend
      #       - backend
      #     filters:
      #       branches:
      #         only: master
