version: 2.1

jobs:
  frontend:
    docker:
      - image: circleci/node:14.5.0-browsers
    working_directory: ~/hamvocke/doppelkopf
    steps:
      - checkout
      - attach_workspace:
          at: ~/hamvocke/doppelkopf
      - restore_cache:
          key: v1-frontend-yarn-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install frontend dependencies
          command: 'pushd frontend && yarn install && popd'
      - save_cache:
          key: v1-frontend-yarn-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
      - run:
          name: Test frontend
          command: 'pushd frontend && yarn test:ci && yarn test:e2e && popd'
      - run:
          name: Build frontend
          command: 'pushd frontend && yarn build && popd'
      - persist_to_workspace:
          root: .
          paths: frontend/dist

  backend:
    docker:
      - image: circleci/python:3.8-node-browsers
    working_directory: ~/hamvocke/doppelkopf
    steps:
      - checkout
      - attach_workspace:
          at: ~/hamvocke/doppelkopf
      - restore_cache:
          key: v1-backend-yarn-{{ checksum "backend/yarn.lock" }}
      - run:
          name: Install backend dependencies
          command: 'pushd backend && make install && popd'
      - save_cache:
          key: v1-backend-yarn-{{ checksum "backend/yarn.lock" }}
          paths:
            - backend/node_modules
      - run:
          name: Test backend
          command: 'pushd backend && make test && popd'

  deploy:
    docker:
      - image: cimg/base:2020.08
    working_directory: ~/hamvocke/doppelkopf
    steps:
      - checkout
      - attach_workspace:
          at: ~/hamvocke/doppelkopf
      - restore_cache:
          key: v1-frontend-yarn-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Docker login
          command: 'echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin'
      - run:
          name: Docker build
          command: |
            touch backend/.env
            docker-compose build
      - run:
          name: Docker push
          command: 'docker-compose push'
      - add_ssh_keys:
          fingerprints:
            - "4b:46:c1:f8:dd:bf:bc:cf:5c:44:c4:5c:4f:8e:1f:22"
      - run:
          name: Copy files
          command: 'scp -o StrictHostKeyChecking=no docker-compose{.prod,}.yml $SSH_USER@$SSH_HOST:/data/doppelkopf/'
      - run:
          name: Start Docker containers
          command: |
            ssh -T $SSH_USER@$SSH_HOST -o StrictHostKeyChecking=no \<< EOF
              cd /data/doppelkopf
              docker-compose pull
              docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
            EOF

workflows:
  version: 2
  build-all:
    jobs:
      - frontend
      - backend
      - deploy:
          requires:
            - frontend
            - backend
          filters:
            branches:
              only: master
